Repository AY2122S1-CS2103T-W11-1/tp, pull requests merged in 2021-10, with the labels that each got.

#43 Sort ingredients by expiry and name
  src/main/java/fridgy/logic/commands/ListCommand.java
  src/main/java/fridgy/logic/commands/exceptions/CommandException.java
  src/main/java/fridgy/logic/parser/AddCommandParser.java
  src/main/java/fridgy/model/Inventory.java
  src/main/java/fridgy/model/Model.java
  src/main/java/fridgy/model/ModelManager.java
  src/main/java/fridgy/model/ingredient/IngredientDefaultComparator.java
  src/main/java/fridgy/model/ingredient/UniqueIngredientList.java
  src/main/java/fridgy/storage/JsonAdaptedIngredient.java
  src/test/java/fridgy/logic/commands/AddCommandTest.java
  src/test/java/fridgy/model/ModelManagerTest.java
  src/test/java/fridgy/model/ingredient/UniqueIngredientListTest.java
  src/test/java/fridgy/storage/JsonAdaptedIngredientTest.java
Labels: type.Task

#58 Remove remnants from Person class
  src/main/java/fridgy/logic/commands/ListCommand.java
  src/main/java/fridgy/model/ReadOnlyRecipeBook.java
  src/main/java/fridgy/model/recipe/Name.java
  src/main/java/fridgy/model/recipe/exceptions/RecipeNotFoundException.java
  src/main/java/fridgy/storage/JsonSerializableRecipeBook.java
Labels: severity.VeryLow

#62 Fix add example command
  src/main/java/fridgy/logic/commands/AddCommand.java
Labels: type.Bug, severity.Medium

#81 Update DG's Design and Implementation
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/IngredientClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/RecipeClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/IngredientClassDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/RecipeClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Documentation

#88 Edit sections on parsing and logic in Developer's Guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#76 Update User Guide to v1.2 and adjust output formatting
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findIngredient1.png
  docs/images/findRecipe1.png
  docs/images/listIngredient1.png
  docs/images/listRecipe1.png
  docs/images/viewRecipe1.png
  src/main/java/fridgy/logic/commands/AddCommand.java
  src/main/java/fridgy/logic/commands/ClearCommand.java
  src/main/java/fridgy/logic/commands/DeleteCommand.java
  src/main/java/fridgy/logic/commands/EditCommand.java
  src/main/java/fridgy/logic/commands/recipe/AddRecipeCommand.java
  src/main/java/fridgy/logic/commands/recipe/DeleteRecipeCommand.java
  src/main/java/fridgy/model/recipe/Recipe.java
  src/main/java/fridgy/ui/RecipeCard.java
  src/main/resources/view/RecipeListCard.fxml
Labels: type.Documentation

#83 base ingredient
  src/main/java/fridgy/model/ingredient/BaseIngredient.java
  src/main/java/fridgy/model/ingredient/Ingredient.java
  src/test/java/fridgy/model/ingredient/BaseIngredientTest.java
  src/test/java/fridgy/model/ingredient/IngredientTest.java
  src/test/java/fridgy/testutil/IngredientBuilder.java
  src/test/java/fridgy/testutil/TypicalBaseIngredients.java
Labels: type.Task
