Repository AY2122S1-CS2103T-W11-1/tp, pull requests merged in 2021-11, with the labels that each got.

#199 Add quantity to ingredient in add recipe command message
  src/main/java/fridgy/logic/commands/recipe/AddRecipeCommand.java
Labels: type.Bug

#112 Update DG use cases for view commands and resolve feedback given
  docs/DeveloperGuide.md
Labels: type.Documentation

#209 V1.4 Merge Delete and MultiDelete into one
  docs/UserGuide.md
  src/main/java/fridgy/commons/core/Messages.java
  src/main/java/fridgy/logic/commands/DeleteCommand.java
  src/main/java/fridgy/logic/commands/MultiDeleteCommand.java
  src/main/java/fridgy/logic/commands/recipe/DeleteRecipeCommand.java
  src/main/java/fridgy/logic/commands/recipe/MultiDeleteRecipeCommand.java
  src/main/java/fridgy/logic/parser/DeleteCommandParser.java
  src/main/java/fridgy/logic/parser/FridgyParser.java
  src/main/java/fridgy/logic/parser/InventoryParser.java
  src/main/java/fridgy/logic/parser/MultiDeleteCommandParser.java
  src/main/java/fridgy/logic/parser/recipe/DeleteRecipeCommandParser.java
  src/main/java/fridgy/logic/parser/recipe/MultiDeleteRecipeCommandParser.java
  src/main/java/fridgy/logic/parser/recipe/RecipeParser.java
  src/test/java/fridgy/logic/commands/DeleteCommandTest.java
  src/test/java/fridgy/logic/commands/MultiDeleteCommandTest.java
  src/test/java/fridgy/logic/commands/recipe/DeleteRecipeCommandTest.java
  src/test/java/fridgy/logic/commands/recipe/MultiDeleteRecipeCommandTest.java
  src/test/java/fridgy/logic/parser/DeleteCommandParserTest.java
  src/test/java/fridgy/logic/parser/MultiDeleteCommandParserTest.java
  src/test/java/fridgy/logic/parser/recipe/DeleteRecipeCommandParserTest.java
  src/test/java/fridgy/logic/parser/recipe/MultiDeleteRecipeCommandParserTest.java
  src/test/java/fridgy/logic/parser/recipe/RecipeCommandParserTestUtil.java
Labels: type.Enhancement, priority.Medium

#213 Minor fixes and UG update for Delete
  docs/UserGuide.md
  src/main/java/fridgy/commons/core/Messages.java
  src/main/java/fridgy/logic/parser/FridgyParser.java
  src/test/java/fridgy/logic/commands/recipe/DeleteRecipeCommandTest.java
Labels: priority.Low, type.Documentation

#214 V1.4 Fix empty field bugs for AddRecipeCommand
  docs/UserGuide.md
  src/main/java/fridgy/logic/commands/recipe/AddRecipeCommand.java
  src/main/java/fridgy/logic/parser/ParserUtil.java
  src/main/java/fridgy/logic/parser/recipe/AddRecipeCommandParser.java
  src/main/java/fridgy/model/recipe/Step.java
  src/test/java/fridgy/logic/parser/ParserUtilTest.java
  src/test/java/fridgy/logic/parser/recipe/AddRecipeCommandParserTest.java
  src/test/java/fridgy/model/recipe/StepTest.java
Labels: type.Bug, priority.High

#140 Change font size, min window size, adjust steps description padding + truncation
  src/main/java/fridgy/ui/RecipeDisplay.java
  src/main/java/fridgy/ui/UiUtil.java
  src/main/resources/view/Main.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug

#225 Reject 'expiry' or 'expiring' tags as userinput
  src/main/java/fridgy/logic/parser/ParserUtil.java
  src/main/java/fridgy/model/tag/Tag.java
  src/test/data/JsonInventoryStorageTest/invalidAndValidIngredientInventory.json
  src/test/data/JsonSerializableInventoryTest/typicalIngredientsInventory.json
  src/test/java/fridgy/logic/commands/ClearCommandTest.java
  src/test/java/fridgy/logic/commands/CommandTestUtil.java
  src/test/java/fridgy/model/InventoryTest.java
  src/test/java/fridgy/model/ingredient/ExpiryStatusUpdaterTest.java
  src/test/java/fridgy/testutil/IngredientBuilder.java
  src/test/java/fridgy/testutil/TypicalIngredients.java
Labels: type.Bug, priority.High

#230 Fix optional steps JSON bug
  src/main/java/fridgy/storage/recipe/JsonAdaptedRecipe.java
  src/test/java/fridgy/storage/recipe/JsonAdaptedRecipeTest.java
Labels: type.Bug, priority.High

#215 Allow user to add ingredients with same name but different expiry dates
  src/main/java/fridgy/model/ingredient/Ingredient.java
  src/test/java/fridgy/logic/commands/AddCommandTest.java
  src/test/java/fridgy/model/ingredient/IngredientTest.java
Labels: type.Bug, priority.High

#234 Update UI implementation for DG
  docs/DeveloperGuide.md
  docs/diagrams/UiStateClassDiagram.puml
  docs/images/LabelledUi.png
  docs/images/UiStateClassDiagram.png
Labels: type.Documentation

#236 Minor changes and bugfixes for Quantity.
  src/main/java/fridgy/logic/parser/ParserUtil.java
  src/main/java/fridgy/model/ingredient/Quantity.java
  src/main/java/fridgy/model/util/QuantityCalc.java
  src/main/java/fridgy/storage/JsonAdaptedIngredient.java
  src/main/java/fridgy/storage/recipe/JsonAdaptedIngredient.java
  src/main/java/fridgy/ui/IngredientCard.java
  src/main/java/fridgy/ui/IngredientDisplay.java
  src/test/java/fridgy/model/QuantityCalcTest.java
  src/test/java/fridgy/model/ingredient/QuantityTest.java
  src/test/java/fridgy/testutil/IngredientUtil.java
Labels: type.Enhancement, type.Bug, priority.High

#238 V1.4 fix ug bugs
  docs/UserGuide.md
Labels: type.Documentation

#247 UG update
  docs/UserGuide.md
  docs/images/fridge.png
  docs/images/ingredientCommands/addCommand1.png
  docs/images/ingredientCommands/addCommand2.png
  docs/images/ingredientCommands/addCommand3.png
  docs/images/ingredientCommands/clearCommand.png
  docs/images/ingredientCommands/clearCommand2.png
  docs/images/ingredientCommands/clearExpired1.png
  docs/images/ingredientCommands/clearExpired2.png
  docs/images/ingredientCommands/deleteCommand1.png
  docs/images/ingredientCommands/deleteCommand2.png
  docs/images/ingredientCommands/editCommand1.png
  docs/images/ingredientCommands/editCommand2.png
  docs/images/ingredientCommands/findIngredient.png
  docs/images/ingredientCommands/findIngredient1.png
  docs/images/ingredientCommands/listIngredient.png
  docs/images/ingredientCommands/listIngredient1.png
  docs/images/ingredientCommands/multideleteCommand.png
  docs/images/ingredientCommands/viewCommand1.png
  docs/images/ingredientCommands/viewIngredient.png
  docs/images/recipeCommands/addRecipe1.png
  docs/images/recipeCommands/addRecipe2.png
  docs/images/recipeCommands/addRecipe3.png
  docs/images/recipeCommands/clearRecipe.png
  docs/images/recipeCommands/clearRecipe1.png
  docs/images/recipeCommands/cookRecipe1.png
  docs/images/recipeCommands/cookRecipe2.png
  docs/images/recipeCommands/cookRecipe3.png
  docs/images/recipeCommands/deleteRecipe1.png
  docs/images/recipeCommands/deleteRecipe2.png
  docs/images/recipeCommands/editRecipe1.png
  docs/images/recipeCommands/editRecipe2.png
  docs/images/recipeCommands/findRecipe.png
  docs/images/recipeCommands/findRecipe1.png
  docs/images/recipeCommands/listRecipe.png
  docs/images/recipeCommands/listRecipe1.png
  docs/images/recipeCommands/multideleteRecipe.png
  docs/images/recipeCommands/viewRecipe.png
  docs/images/recipeCommands/viewRecipe1.png
  src/main/java/fridgy/model/ingredient/Ingredient.java
  src/main/java/fridgy/model/ingredient/Name.java
  src/test/java/fridgy/logic/commands/recipe/CookRecipeCommandTest.java
  src/test/java/fridgy/model/InventoryTest.java
  src/test/java/fridgy/model/ingredient/BaseIngredientTest.java
Labels: priority.High, type.Documentation

#260 Change README screeenshot
  docs/images/Ui.png
Labels: type.Documentation
